/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "buttons": {
        "back": string;
        "admin": string;
        "products": string;
        "create": string;
        "delete": string;
        "change_language": string;
    };
    "phrases": {
        "start": {
            "enter": string;
        };
        "admin": {
            "enter": string;
        };
        "products": {
            "enter": string;
        };
        "product_create": {
            "enter": string;
        };
        "product_delete": {
            "enter": string;
        };
        "product_delete_seriously": {
            "enter": string;
        };
        "products_not-found": {
            "enter": string;
        };
        "change_language": {
            "enter": string;
        };
    };
    "languages": {
        "en": string;
        "ru": string;
    };
    "scenes": {
        "start": {
            "enter": string;
        };
        "admin": {
            "enter": string;
        };
        "products": {
            "enter": string;
        };
        "product_create": {
            "enter": string;
        };
        "product_delete": {
            "enter": string;
        };
        "change_language": {
            "enter": string;
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
